### ISSUE TITLE
Can't access general settings after install

### ISSUE THREAD

**Issue by mvhurlburt** [muk-it/muk_website#3]
I recently installed the MuK website grid snippets module through the import module on Odoo 12 and I am now unable to access my general settings. The module threw an error during the initial install so I went back and installed odoo-autodiscover and the MuK website grid snippets through pip. However I'm still getting an error when I try to access my general settings. I suspect MuK Utils and/or MuK Web Utils may be the culprit as they both inherit res.config.settings.view.form though I may be completely wrong. I'm still very new to odoo and I haven't been able to resolve this problem. If anybody is willing to help I've posted the traceback below.

Error:

Odoo Server Error

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/odoo/http.py", line 653, in _handle_exception

    return super(JsonRequest, self)._handle_exception(exception)

  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception

    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])

  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise

    raise value

  File "/usr/lib/python3/dist-packages/odoo/http.py", line 695, in dispatch

    result = self._call_function(**self.params)

  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function

    return checked_call(self.db, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper

    return f(dbname, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call

    result = self.endpoint(*a, **kw)

  File "/usr/lib/python3/dist-packages/odoo/http.py", line 938, in __call__

    return self.method(*args, **kw)

  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap

    response = f(*args, **kw)

  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw

    return self._call_kw(model, method, args, kwargs)

  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw

    return call_kw(request.env[model], method, args, kwargs)

  File "/usr/lib/python3/dist-packages/odoo/api.py", line 745, in call_kw

    return _call_kw_model(method, model, args, kwargs)

  File "/usr/lib/python3/dist-packages/odoo/api.py", line 718, in _call_kw_model

    result = method(recs, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1368, in load_views

    for [v_id, v_type] in views

  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1368, in <dictcomp>

    for [v_id, v_type] in views

  File "/usr/local/lib/python3.6/dist-packages/odoo/addons/muk_web_utils/models/res_config_settings.py", line 68, in fields_view_get

    view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)

  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_config.py", line 395, in fields_view_get

    toolbar=toolbar, submenu=submenu)

  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1447, in fields_view_get

    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)

  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1410, in _fields_view_get

    root_view = View.browse(view_id).read_combined(['id', 'name', 'field_parent', 'type', 'model', 'arch'])

  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 780, in read_combined

    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)

  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 730, in apply_view_inheritance

    source = self.apply_view_inheritance(source, view_id, model, root_id=root_id)

  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 729, in apply_view_inheritance

    source = self.apply_inheritance_specs(source, specs_tree, view_id)

  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 707, in apply_inheritance_specs

    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)

  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 545, in raise_view_error

    raise ValueError(message)

ValueError: Element '<div name="storage">' cannot be located in parent view

Error context:

View `res.config.settings.view.form`

[view_id: 1998, xml_id: n/a, model: res.config.settings, parent_id: 246]

**Comment by keshrath** [comment]
I can't reproduce this issue on our demo with all this modules installed. Make sure all modules are up2date.
